# Generated by Django 4.1.1 on 2022-09-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('mtd', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('cancel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('ostation', models.CharField(max_length=50)),
                ('dstation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('tno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('atime', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.station')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('nos', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('cls', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trains')),
            ],
        ),
    ]
